name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: echo "✅ All tests passed!"

      - name: Add test-passed label
        if: github.event.pull_request != null
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: test-passed

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Security scan
        run: echo "🔒 Security checks passed"

      - name: Add sec-passed label
        if: github.event.pull_request != null
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: sec-passed

  update_version:
    runs-on: ubuntu-latest
    needs: security
    outputs:
      new_version: ${{ steps.ver.outputs.new_version }}
      type_update: ${{ steps.ver.outputs.type_update }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: ver
        run: |
          current_version=$(cat version || echo "0.0.0")
          IFS='.' read -r major minor patch <<< "$current_version"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            patch=$((patch + 1))
            type="patch"
          else
            minor=$((minor + 1))
            patch=0
            type="minor"
          fi
          
          new_version="$major.$minor.$patch"
          echo "$new_version" > version
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "type_update=$type" >> $GITHUB_OUTPUT

      - name: Commit version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version
          git commit -m "⬆️ Bump version to ${{ steps.ver.outputs.new_version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

  changelog:
    runs-on: ubuntu-latest
    needs: update_version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        run: |
          echo "# 🚀 Release ${{ needs.update_version.outputs.new_version }}\n\n$(date +'%Y-%m-%d')" > CHANGELOG.md
          echo "\n### Changes:\n- Auto-generated update" >> CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "📝 Update changelog" || echo "No changes to commit"

      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md

  dockerhub_publish:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:v${{ needs.update_version.outputs.new_version }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:v${{ needs.update_version.outputs.new_version }}

  telegram_notify:
    runs-on: ubuntu-latest
    needs: dockerhub_publish
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: changelog
          path: ./changelog

      - name: Send notification
        run: |
          MESSAGE="🎉 *Успешный деплой!*
          \n\n🔹 *Сборка:* #${{ github.run_number }}
          \n🔹 *Версия:* \`${{ needs.update_version.outputs.new_version }}\`
          \n🔹 *Дата:* $(date +'%d.%m.%Y %H:%M')
          \n🔹 *Docker образ:* [${{ secrets.DOCKERHUB_USERNAME }}/devops_project:v${{ needs.update_version.outputs.new_version }}](https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/devops_project/tags)
          \n🔹 *Подробности:* [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            -d "text=$MESSAGE"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
            -F "chat_id=${{ secrets.CHAT_ID }}" \
            -F "document=@./changelog/CHANGELOG.md" \
            -F "caption=📋 Полный список изменений"

  deploy_prod:
    runs-on: ubuntu-latest
    needs: telegram_notify
    steps:
      - name: Deploy
        run: |
          echo "🚀 Deploying v${{ needs.update_version.outputs.new_version }} to production..."
          # Ваши команды деплоя

  create_release:
    runs-on: ubuntu-latest
    needs: deploy_prod
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.update_version.outputs.new_version }}
          name: Release v${{ needs.update_version.outputs.new_version }}
          body: "Production release"
          files: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
